---
title: "R Notebook"
output: html_notebook
---


```{r}
library(forcats)
```


```{r}
df <- forcats::gss_cat
df <- df[sample(nrow(df), 10),1:4]
df
```


```{r}
levels(df$marital)
```


```{r}
attributes(df$marital)
```



```{r}
library(data.table)
```


```{r}
setDT(df)
```


```{r}
setattr(df$marital, 'levels', c('answer', 'nevermarried', 'sepa','div','wid','marr'))
```

```{r}

```


```{r}
df <- forcats::gss_cat
df <- df[sample(nrow(df), 10),1:4]
df
```


```{r}
levels(df$marital)[levels(df$marital)=='marr'] <- "mark"
```



```{r}
levels(df$marital) <- gsub('^Widowed$', "widow_new", levels(df$marital))
```


```{r}
require(graphics)

bymedian <- with(InsectSprays, reorder(spray, count, median))

```

```{r}
boxplot(count ~ bymedian, data = InsectSprays,
        xlab = "Type of spray", ylab = "Insect count",
        main = "InsectSprays data", varwidth = TRUE,
        col = "lightgray")
```


```{r}
set.seed(123)
df <- forcats::gss_cat
df <- df[sample(nrow(df), 10),1:4]
setDT(df)
```


```{r}
df
```


```{r}
df[, marital:=as.character(marital)]

```


```{r}
df[marital=='Married', marital:= "new_married"]
```



```{r}
#df[, marital:=factor(marital)]
```


```{r}
df[, marital:=factor(marital, levels = c("new_married", "Widowed", "Never married"))]
```


```{r}
df[,marital:=as.integer(marital)]
```


```{r}

```



```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```



```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```



```{r}

```


```{r}

```


```{r}

```


```{r}

```



```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```



```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```



```{r}

```


```{r}

```


```{r}

```


```{r}

```



```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```



```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```



