---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r}

for(i in 1:6) { 
    nam <- paste("r", i, sep = ".")
    print(nam)
    print(1:i)
assign(nam, 1:i)
print(nam)
}
```

```{r}
x <- cbind(a = 1:3, pi = pi)
x
attributes(x)
```

```{r}
# integer
int <- 1:5
```

```{r}
typeof(int)
```

```{r}
class(int)
```

```{r}
int
```

```{r}
is.numeric(int)
```

```{r}
is.integer(int)
```

```{r}
is.double(int)
```



```{r}
int <- int+1
int
```

```{r}
typeof(int)
```

```{r}
class(int)
```

```{r}
int <- 1:5
int
```
```{r}
class(int)
```

```{r}
int <- int+ 1L
int
```

```{r}
class(int)
```

```{r}
typeof(int)
```
```{r}
vec <- c(1,2,3,4,5)
```

```{r}
class(vec)
```

```{r}
typeof(vec)
```

```{r}
vec_int <- c(1L, 2L, 3L,4L,5L)
```

```{r}
vec_int
```

```{r}
class(vec_int)
```

```{r}
typeof(vec_int)
```
```{r}
is.numeric(vec_int)
```
#### NA , NaN, NULL, Inf, -Inf

```{r}

```

#### apply 
##### for array, 2d matrix or higher dimension, 
return array or matrix

```{r}
X <- matrix(rnorm(30), nrow=5, ncol=6)
X
```

```{r}
res <- apply(X, MARGIN = 2, FUN = sum)
res
```

```{r}
str(res)
```

colMeans, rowMeans, colSums, rowSums better for similar situation.

```{r}
colSums(X)
```

#### lapply

input list, output list

```{r}
x <- list(a = 1, b = 1:3, c = 10:100)
x
```

```{r}
lapply(x, length)
```

```{r}
mt <- lapply(mtcars, sum)
```

```{r}
mt
```

```{r}
str(mt)
```


```{r}
unlist(mt)
```
```{r}
mt_v <- unlist(mt)
```

```{r}
str(mt_v)
```
#### sapply

```{r}
library(dplyr)
library(data.table)
set.seed(123)
n = 5e7
k = 5e5
x = runif(n)
grp = sample(k, n, TRUE)

timing = list()
```


```{r}
df <- mtcars
```

```{r}
mat <- matrix(rnorm(400000), nrow =40000, ncol = 10 )
df <- as.data.frame(mat)

```

```{r}
names(df) <- LETTERS[1:10]
```

```{r}
dt <- as.data.table(df)
```


```{r}
star_time <- Sys.time()
#bs <- lapply(df, sum)
#bs <- colSums(df)
dt_t <- dt[, lapply(.SD, sum)]
#dp <- purrr::map(df, function(x) sum(x))

end_time <- Sys.time()
diff_time <- end_time - star_time
diff_time
```

```{r}
res_apply <- apply(mtcars, c(1,2), mean)
res_apply
```

```{r}
str(res_apply)
```

```{r}
x <- list(a = 1, b = 1:3, c = 10:100)
```

```{r}
va <- vapply(x, FUN = length, FUN.VALUE = 0L)
```

```{r}
test <- list(a = c(1, 3, 5), b = c(2,4,6), c = c(9,8,7))

sapply(test, max)
```

```{r}
test$d <- c("a", "b", "c")

#sapply(test, max)
```

