---
title: "R Notebook"
output: html_notebook
---

```{r}
Sys.time()
```


```{r}
as.numeric(Sys.time())
```


```{r}

class(Sys.time())
```

```{r}
class(Sys.Date())
```
```{r}
Sys.Date()
```


```{r}
attributes(Sys.time())
```


```{r}
as.POSIXct(Sys.time())
```



```{r}
as.POSIXlt(Sys.time())
```


```{r}
unlist(as.POSIXlt(Sys.time()))
```
 
 - [lubridate webpage](https://lubridate.tidyverse.org)
 - [lubridate paper](https://www.jstatsoft.org/article/view/v040i03)
 - [the-ultimate-opinionated-guide-to-base-r-date-format-function](https://www.r-bloggers.com/2019/04/the-ultimate-opinionated-guide-to-base-r-date-format-functions/)

```{r}
library(lubridate)
```


```{r}
df <- lakers[1:10, 1:5]
str(df)
```


```{r}
mode(df$date)
```



```{r}
typeof(df$date)
```


```{r}
class(df$date)
```

```{r}
df <- lakers[sample(nrow(lakers), 10), 1:5]

```


```{r}
df$date <- strptime(as.character(df$date),format = "%Y%m%d")
```


```{r}
str(df)
```

```{r}
weekdays(df$date)
```

```{r}
y2 <- as.POSIXlt("2015-10-22")
y1 <- as.POSIXlt("2018-10-22")
y1-y2
```
```{r}
as.numeric(difftime("2015-10-21","2013-8-15"))
```
```{r}
dt <- y1-y2
```

```{r}
attributes(dt)
```
```{r}
attr(dt,"units")
```
```{r}

```


```{r}
difftime("2014-02-06","2014-07-06")
```



```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```



```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```



```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```



```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```



```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```



```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```



```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```



```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```



```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```



```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```



```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```



```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```



```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```

